# - name: install Docker
#   hosts: workers
#   become: true
#   roles:
#     ## - Docker
#     # - jenkins
#     # - gitlab
#     # - sonarqube
#     ## - Nodejs
#     ## - python
#     ## - Jee
#     ## - Nginx

- name: install using DOCKER COMPOSE
  hosts: workers
  become: true
  tasks:
    - name: copy Docker Compose files
      copy:
        src: files/docker-compose.yml
        dest: /tmp/docker-compose.yml

    - name: copy Dockerfile.jenkins file
      copy:
        src: files/Dockerfile.jenkins
        dest: /tmp/Dockerfile.jenkins

    - name: Install pip3
      become: true
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose

    # use files parameter to use multiple docker-compose.yml files
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /tmp
        files:
        - docker-compose.yml
