version: "3"
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://f4345433f02c.mylabserver.com:8000'
        gitlab_rails['initial_root_password'] = ''
    ports:
      - '8000:8000'
      - '8446:8443'
      - '25:22'
    volumes:
      - ./volumes/gitlab-config:/etc/gitlab
      - ./volumes/gitlab-logs:/var/log/gitlab
      - ./volumes/gitlab-data:/var/opt/gitlab
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: always
    hostname: 'jenkins'
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
      - '/var/run/docker.sock:/var/run/docker.sock'
  sonarqube:
    image: 'sonarqube:7.6-community'
    ports:
      - '9092:9000'
    volumes:
      - ./volumes/sonarqube_conf:/opt/sonarqube/conf
      - ./volumes/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube_logs:/opt/sonarqube/logs
      - ./volumes/sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
